### ISSUE TITLE
v2.2.1 release

### ISSUE THREAD

**Issue by Moc** [e107translations/Polish#3]
Hi @akogo1 , 

Thank you for updating the Polish language files. Great work 👍 

I have just corrected the v2.1.1 release. There were two issues: 

1) The latest files are not in the Github repository, they are just added in the ZIP you uploaded in the releases section. You need to make sure that you push the latest files to the Github repository. I have done that for you now here: https://github.com/e107translations/Polish/commit/989e52eadfdd0202a02b2975526f19840f3e852a

Please see https://guides.github.com/ for more information on how to use Github and how to commit and push files to repositories. 

2) The tag of the release was missing the `v` prefix. When releasing, please read the instructions here carefully: https://github.com/e107translations/Translator-Information
("Enter for Tag version the current version. eg. v2.1.5 (make sure you include the v )"

I have re-released the correct version now.

**Comment by akogo1** [comment]
ok, I understand. Thank you.
